### ISSUE TITLE
{{rootURL}} changed to {{this.rootURL}}

### ISSUE THREAD

**Issue by vlascik** [ember-codemods/ember-no-implicit-this-codemod#100]
Before:
```hbs
    {{#link-to "index" class="navbar-brand"}}<img src="{{rootURL}}images/logo3.png">{{/link-to}}
  </div>
```

After:
```hbs
{{#link-to "index" class="navbar-brand"}}<img src="{{this.rootURL}}images/logo3.png">{{/link-to}}
  </div>
```

Current github master (3df3c19d3baa35b6f908fa68bfb6efe1ce632aec) + current master of telemetry-helpers (as the currently released version breaks on Windows)

**Comment by NullVoxPopuli** [comment]
Where is rootURL defined?

**Comment by vlascik** [comment]
I think it used to be some sort of global variable or a helper, but it seems that doesn't work anymore, and the new router helpers (https://github.com/emberjs/rfcs/pull/0391) are not implemented yet. I'll close this.
