### ISSUE TITLE
Codemod is too liberal at appending `this.`

### ISSUE THREAD

**Issue by patocallaghan** [ember-codemods/ember-no-implicit-this-codemod#11]
Currently if some property is found to **NOT** be a local property, block param, action, helper, component etc it's automatically assumed to be a local property and has `this.` prepended to it. Personally I think this is too liberal an assumption and we can't always assume this. A simplified use case that didn't transform as I'd expect was the following:

``` js
// some-component JS definition
export default Component.extend({
  foo: 'foo',
});
```

```hbs
<!-- some-component invocation -->
<SomeComponent
  @bar="bar"
/>

<!-- some-component HBS definition -->
<!-- Before: the codemod runs -->
<!-- Here we are using the "local" foo property and the passed in "bar" argument -->
{{foo}}
{{bar}}

<!-- After: the codemod runs -->
{{this.foo}}
{{this.bar}}

<!-- In reality what it should be -->
{{this.foo}}
{{@bar}}
```

I'm not sure if we can ever deduce whether something should have an `@` in front of it. But in the case where we can't accurately 100% know if it should have a `this.` or `@` in front of it I'd prefer if we didn't try to transform and instead just log out those ambiguous cases. We do similar in the angle bracket codemod with positional params and other ambiguous cases. 

This logic is contained within the `doesTokenNeedThis` function in `helpers/plugin.js`.

https://github.com/ember-codemods/ember-no-implicit-this-codemod/blob/a7fe0595197dd3a812c15746b2a442ca9153a9b1/transforms/no-implicit-this/helpers/plugin.js#L67-L101

At the end of this function we return `true` where I think we should instead return `false`. Worth noting that returning `false` doesn't cause any of the tests to fail, they are still 🍏.

So with this change my workflow to migrating a template would involve:
1. Run this codemod on said template
2. turn on `no-implicit-this` template-lint rule
3. Fix up the ambiguous errors on a case-by-case basis

**Comment by rwjblue** [comment]
> ```
> 
> {{this.foo}}
> {{@bar}}
> ```

I disagree. Adding `this.` is **always** correct for `Ember.Component` based components (and we need the runtime telemetry gathering for that), in your case it is **basically** impossible to know (programmatically) if `@bar` or `this.bar` is better. Specifically, there could be code (one of its parent classes, a mixin, some helper invoked that is passed `this`, etc) that mutates `this.bar` in some way.

**Comment by patocallaghan** [comment]
Oh interesting, I didn't know that was the case with `Ember.Component`. Just tested `{{this.bar}}` and `{{@bar}}` and both worked 🤦‍♂ 

Do you think this is something that could be configurable? By default it could add `this.` everywhere it can, but if opted out it just leaves alone those ones it can't deduce from the telemetry data (`this.` or `@` needs to manually figured out)?

If not, feel free to close this issue.

**Comment by rwjblue** [comment]
Yes, I think it can be configurable, but I really do not see how we can reliably decide to use `@` or not. I think the only cases that can always use `@` are template only components?

**Comment by patocallaghan** [comment]
I don't think the codemod should decide whether to use `@` or `this.` either. The onus should on the developer running the codemod to decide by looking at the corresponding JS file and the component's invocation call sites, and manually updating the template.

**Comment by rwjblue** [comment]
Right, exactly. As a general process, we would probably migrate to named arguments as part of changing the base class.

**Comment by patocallaghan** [comment]
I've put together a PR here https://github.com/ember-codemods/ember-no-implicit-this-codemod/pull/12
