### ISSUE TITLE
`data-` attribute positioning causes invalid transformation

### ISSUE THREAD

**Issue by patocallaghan** [ember-codemods/ember-no-implicit-this-codemod#15]
I found a number of my templates failed with compilation errors when I ran this codemod on them. They were all failing due to the following scenario.

### Before
```hbs
<Select
  data-test-select
  @items={{foo}}
  @onSelectItem={{action "setValue"}}
  @selectedValue={{foo}}
/>
```

### Expected
```hbs
<Select
  data-test-select
  @items={{this.foo}}
  @onSelectItem={{action "setValue"}}
  @selectedValue={{this.foo}}
/>
```

### Result
Notice all the arguments and attributes are placed side-by-side together with no spacing between them. This causes a template compilation error.
```hbs
<Select
  data-test-select@items={{this.foo}}@onSelectItem={{action "setValue"}}@selectedValue={{this.foo}}
/>
```

The issue seems to be specifically related to the positioning of the `data-` attribute being first and the fact it doesn't have an assignment. The following two inputs transform with no issues:

```hbs
<Select
  data-test-select="true"
  @items={{this.foo}}
  @onSelectItem={{action "setValue"}}
  @selectedValue={{this.foo}}
/>

<Select
  @items={{this.foo}}
  @onSelectItem={{action "setValue"}}
  @selectedValue={{this.foo}}
  data-test-select
/>
```

**Comment by rwjblue** [comment]
This is almost certainly an issue with ember-template-recast (reported in https://github.com/ember-template-lint/ember-template-recast/issues/83).
