### ISSUE TITLE
[Bug] Newline after `as` causes an invalid transform

### ISSUE THREAD

**Issue by patocallaghan** [ember-codemods/ember-no-implicit-this-codemod#24]
This is more than likely an ember-template-recast bug but opening it here to start. It appears having a newline AFTER the `as` keyword when yielding properties causes an invalid transform. Not to make the invalid transform you have to modify a property on the line. For example:

### Input
``` hbs
<MyComponent @someArg={{value}} as
|myComponent|>
</MyComponent>
```

### Expected output
``` hbs
<MyComponent @someArg={{this.value}} as
|myComponent|>
</MyComponent>
```

### Actual output
``` hbs
<MyComponent @someArg={{this.value}} <MyComponent @someArg={{this.value}} as
|myComponent|>
</MyComponent>
```

Notice the `<MyComponent` has been duplicated inline and causes a template compile error due to invalid syntax.

If the input looks like the following with the yielded property on the *same line* as the `as`, the transform works as expected

``` hbs
<MyComponent @someArg={{value}} as |myComponent|>
</MyComponent>
```

**Comment by NullVoxPopuli** [comment]
Just checked if this was still an issue, even with everything upgraded to latest. Yup. still an issue :+1:

**Comment by rwjblue** [comment]
We should probably move this over to ember-template-recast, it isn't really an issue here...
