### ISSUE TITLE
README is missing `ember serve`

### ISSUE THREAD

**Issue by Turbo87** [ember-codemods/ember-no-implicit-this-codemod#27]
The README file does not mention that `ember serve` needs to run in the background for the codemod to be able to do its thing. It looks like #8 tried to fix this, but the MR has merge conflicts and changes other things too.

**Comment by NullVoxPopuli** [comment]
whoops. Forgot about that PR. will update. thanks!

**Comment by NullVoxPopuli** [comment]
resolved in #8
