### ISSUE TITLE
Codemod is adding `this.` to *everything*

### ISSUE THREAD

**Issue by Turbo87** [ember-codemods/ember-no-implicit-this-codemod#28]
I ran `npx ember-no-implicit-this-codemod http://localhost:4200 app/` and this is what happened...

<img width="767" alt="Bildschirmfoto 2019-10-04 um 12 27 48" src="https://user-images.githubusercontent.com/141300/66202354-d50e7e80-e6a5-11e9-8c7e-30df5b48c179.png">

to reproduce, https://github.com/skylines-project/skylines/tree/4af6a8173ccddd5339f79c2a44a97615b682231c/ember is the commit that I ran this on

**Comment by rwjblue** [comment]
The most obvious thing here is that we should not be transforming **any** built-in's (e.g. `if`,`each`,`debugger`,`log`,`each-in`,`action`,`query-params`, etc).
