### ISSUE TITLE
Drops deeply nested {{else}}

### ISSUE THREAD

**Issue by jrjohnson** [ember-codemods/ember-no-implicit-this-codemod#31]
Not sure at what level this happens, this is as close to a simple case as I could get anything else I could think of to make it less complicated didn't have this issue.

```
{{#each something as |obj|}}
  {{#if obj.foo}}
    111
  {{else}}
    222
    <div>
      {{#if obj.foo}}
        {{#if (eq obj.bar "foo")}}
          333
        {{else}}
          444
        {{/if}}
        <span>
          {{#if obj.foo}}
            555
          {{/if}}
        </span>
      {{else if obj.bar}}
        666
      {{else}}
        777
      {{/if}}
    </div>
  {{/if}}
{{/each}}
```
After running the codemod the `else 777` section is completely removed.

~I attempted to create a test to duplicate this, but it does not happen in the tests, so it may have something to do with the running server. In case that's the issue I created a reproduction repo at https://github.com/jrjohnson/reproduction-implicit-this-mod-nested~ (edit: fixed failing test / copy paste error)

**Comment by patocallaghan** [comment]
@jrjohnson this is potentially an ember-template-recast issue.

@rwjblue @NullVoxPopuli would that be correct?

**Comment by rwjblue** [comment]
Yes, https://github.com/ember-template-lint/ember-template-recast/issues/149 was filed yesterday for (what seems like) the same issue.

**Comment by NullVoxPopuli** [comment]
@jrjohnson is this still an issue? it looks like the latest no-implicit-this codemod contains the update in ember-template-recast, so I'm going to close this for. If anything comes up, feel free to open another issue! <3

**Comment by jrjohnson** [comment]
No it is fixed. Do you want to merge in the now passing test in #32 or should I just close that?

**Comment by NullVoxPopuli** [comment]
I'd close it, since it was an issue with template-recast. thanks though!
