### ISSUE TITLE
Render modifiers prefixed with `this.`

### ISSUE THREAD

**Issue by Turbo87** [ember-codemods/ember-no-implicit-this-codemod#42]
I've used the `didInsert` modifier from `@ember/render-modifiers` in some templates and they are getting replaced with `this.didInsert`.

**Comment by NullVoxPopuli** [comment]
This should hopefully be fixed when #33 is fixed with the changes in #39

**Comment by NullVoxPopuli** [comment]
Confirmed bug here: https://github.com/ember-codemods/ember-no-implicit-this-codemod/pull/44

**Comment by NullVoxPopuli** [comment]
@Turbo87 is this still an issue? or do your recent PRs resolve this?

**Comment by Turbo87** [comment]
yep, should be resolved by #62
