### ISSUE TITLE
components are prefixed with `this` for complex structured apps

### ISSUE THREAD

**Issue by suchitadoshi1987** [ember-codemods/ember-no-implicit-this-codemod#45]
For an app that has multiple apps co-located or if there are components invoked from addons that reside outside of the project, the component gets prefixed with `this` when running the codemod.

**Comment by NullVoxPopuli** [comment]
Hi there! Thanks for the report!
Is there anyway you can provide some info about your project layout, where the component lives, etc?

**Comment by rwjblue** [comment]
@suchitadoshi1987 - Lets make a small reproduction repo (should use in-repo addons, [ember-holy-futuristic-template-namespacing-batman](https://github.com/rwjblue/ember-holy-futuristic-template-namespacing-batman), and components inside nested folders), should be a fun little exercise.

**Comment by suchitadoshi1987** [comment]
@rwjblue @NullVoxPopuli Here is an example which has a couple of in-repo-addons as well as usage of [ember-holy-futuristic-template-namespacing-batman](https://github.com/rwjblue/ember-holy-futuristic-template-namespacing-batman) syntax.
Here is the Repo:
https://github.com/lbdm44/overly-complex-ember-storefront
AND
```npx ember-no-implicit-this-codemod http://localhost:4200 lib/item-description/addon/templates/components/item-detail.hbs``` is the codemod command

My hunch is that this is more of an issue with the missing support for the `$` syntax than anything else.

**Comment by rwjblue** [comment]
Ya, makes sense. I think our module mapping needs to know what $ does in this context. 

Seems like this is where we are building up a list of the "non-this" things:

https://github.com/ember-codemods/ember-no-implicit-this-codemod/blob/210145774d21f7227a06f8147a23f46950673265/transforms/no-implicit-this/helpers/plugin.js#L105-L124

It seems like it is pushing the component name directly there (perhaps still including the root path?), and we need to ensure $ usage is also accommodated...

**Comment by rwwagner90** [comment]
I'm seeing this issue too. It's taking components like this: `{{action-status-list` and making them `{{this.action-status-list`. Perhaps we could ignore anything starting with `{{` or `{{#`?

**Comment by NullVoxPopuli** [comment]
@rwwagner90 that may be a different issue.
couple questions for potential paths:
 - is `action-status-list` from an addon?
   - full addon or in-repo?
 - do you have telemetry data?
   - I've heard reports of telemetry data failing to be collected recently :(
 - which OS are you on?

**Comment by rwwagner90** [comment]
@NullVoxPopuli I am on Mac, and that component is not from an addon. However, we do use pods for components, so it's possible it did not find those components for that reason.

**Comment by NullVoxPopuli** [comment]
Ah, yup. Pods would do it. We need to update telemetry helpers to support pods and co-location.

**Comment by rwwagner90** [comment]
@NullVoxPopuli so pods should work now?

**Comment by NullVoxPopuli** [comment]
@rwwagner90 I don't think so. I think GitHub auto-closed this issue by mistake.
I mostly just don't know how the ember-holy-futuristic-template-namespacing-batman support would affect pods. But maybe I've forgotten too much of how things work. If you could give 0.8.0 a go, and confirm that this is still a big, that'd be fantastic!

**Comment by Turbo87** [comment]
pods support is tracked in #36 and the batman addon is supported now, so I'll go ahead and close this issue again :)
