### ISSUE TITLE
'data-test-' attributes are incorrectly prefixed with 'this' for curly bracket components

### ISSUE THREAD

**Issue by chbonser** [ember-codemods/ember-no-implicit-this-codemod#48]
`data-test-` attributes are prefixed with `this` for curly bracket invoked components. Example diff:

```
-{{#paper-card data-test-job-profile-status as |card|}}
+{{#paper-card this.data-test-job-profile-status as |card|}}
```

The same attributes are handled properly for angle bracket invoked components.

I suppose I could run https://github.com/ember-codemods/ember-angle-brackets-codemod first. If that is the expectation then perhaps adding a note to the readme would be called for.

**Comment by suchitadoshi1987** [comment]
@chbonser Could you confirm if this is happening only for valueless data params?

**Comment by chbonser** [comment]
@suchitadoshi1987, you are correct.

**Comment by suchitadoshi1987** [comment]
@chbonser https://github.com/ember-codemods/ember-no-implicit-this-codemod/pull/51 should fix that issue

**Comment by suchitadoshi1987** [comment]
@chbonser try setting the flag `--dontAssumeThis=true` when you are running the codemod, that would potentially fix the issue too

**Comment by Turbo87** [comment]
@suchitadoshi1987 https://github.com/simplabs/ember-test-selectors-params-codemod 😉

**Comment by suchitadoshi1987** [comment]
oh... that's even better :)

**Comment by chbonser** [comment]
That's great. Thanks @Turbo87
