### ISSUE TITLE
default `dontAssumeThis` value to `true`

### ISSUE THREAD

**Issue by suchitadoshi1987** [ember-codemods/ember-no-implicit-this-codemod#52]
Currently, we have the default value of `dontAssumeThis` set to `false`. This means that everything that the codemod couldn't find would be prefixed with `this`
There are a number of use cases where we wouldn't want to assume `this` to be prefixed by default.
Eg:
```{{foo bar=baz.biz/bang}}```
converts to
```{{foo bar=this.baz.biz/bang}}```

In this case, `baz` is not a property defined in the `foo.js` component, instead, its an argument passed in from the consumer.
Also, for cases with `data-*` selectors, they get prefixed with `this` as well due to our default settings.

Suggestion: Set the `dontAssumeThis` value to `true` instead of `false`

**Comment by Turbo87** [comment]
> In this case, `baz` is not a property defined in the `foo.js` component, instead, its an argument passed in from the consumer.

I think in that case it is totally valid to use `this` since the argument will still be assigned to the corresponding property on the JS class

**Comment by Turbo87** [comment]
Closing this as `dontAssumeThis` no longer exists
